apiVersion: cilium.io/v2alpha1
kind: CiliumBGPClusterConfig
metadata:
  name: unifi
spec:
  nodeSelector: # Ensures this BGP config applies to the specified RPi nodes
    matchLabels:
#      topology.kubernetes.io/region: my-home
      topology.kubernetes.io/zone: announce
  bgpInstances:
    - name: "cloudfleet-bgp" # Name of this BGP instance
      localASN: 65001 # ASN for the K8s cluster's BGP
      peers:
        - name: unifi # Name of the peer (UDM Pro)
          peerASN: 65000 # ASN of the UDM Pro
          peerAddress: "192.168.34.1" # IP address of your UDM Pro on the relevant LAN
          peerConfigRef:
            name: unifi # References the CiliumBGPPeerConfig defined above