router bgp 65000
  bgp bestpath as-path multipath-relax
  no bgp ebgp-requires-policy
  bgp router-id 192.168.34.1
  neighbor dev-clus-core peer-group
  neighbor dev-clus-core remote-as external
  neighbor 192.168.34.40 peer-group dev-clus-core
  neighbor 192.168.34.41 peer-group dev-clus-core
  neighbor 192.168.34.42 peer-group dev-clus-core
  neighbor 192.168.34.43 peer-group dev-clus-core
  neighbor 192.168.34.44 peer-group dev-clus-core
  neighbor 192.168.34.45 peer-group dev-clus-core